# Generated by Django 5.1.7 on 2025-03-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WaterInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("times", models.DateTimeField(verbose_name="上报时间")),
                ("temperature", models.FloatField(verbose_name="气温")),
                ("humidity", models.FloatField(verbose_name="湿度")),
                ("winddirection", models.CharField(max_length=4, verbose_name="风向")),
                ("windpower", models.FloatField(verbose_name="风力")),
                ("rains", models.FloatField(verbose_name="桥东村降水量")),
                ("waterlevels63000120", models.FloatField(verbose_name="东坑溪水位")),
                ("rains63000100", models.FloatField(verbose_name="库区降水")),
                ("waterlevels63000100", models.FloatField(verbose_name="库区水位")),
                ("waterlevels", models.FloatField(verbose_name="桥东村水位")),
            ],
        ),
    ]
