# Generated by Django 5.1.9 on 2025-06-22 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaWeatherInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("times", models.DateTimeField(verbose_name="上报时间")),
                ("city", models.CharField(max_length=20, verbose_name="城市")),
                (
                    "county",
                    models.CharField(db_index=True, max_length=20, verbose_name="区/县"),
                ),
                ("temperature", models.FloatField(verbose_name="气温")),
                ("humidity", models.FloatField(verbose_name="湿度")),
                ("winddirection", models.CharField(max_length=4, verbose_name="风向")),
                ("windpower", models.FloatField(verbose_name="风力")),
            ],
            options={
                "verbose_name": "区域气象信息",
                "verbose_name_plural": "区域气象信息",
            },
        ),
        migrations.CreateModel(
            name="StationInfo",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="站点编号",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="站名")),
                ("city", models.CharField(max_length=20, verbose_name="城市")),
                ("county", models.CharField(max_length=20, verbose_name="区/县")),
                ("longitude", models.FloatField(verbose_name="经度")),
                ("latitude", models.FloatField(verbose_name="纬度")),
                ("flood_limit", models.FloatField(null=True, verbose_name="汛限水位")),
                ("guaranteed", models.FloatField(null=True, verbose_name="保证水位")),
                ("warning", models.FloatField(null=True, verbose_name="警告水位")),
            ],
            options={
                "verbose_name": "站点",
                "verbose_name_plural": "站点列表",
            },
        ),
        migrations.CreateModel(
            name="Statistics",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField(verbose_name="年")),
                ("month", models.IntegerField(verbose_name="月")),
                ("day", models.IntegerField(verbose_name="日")),
                (
                    "station",
                    models.ForeignKey(
                        db_column="station_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="api.stationinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "告警统计",
                "verbose_name_plural": "告警统计",
            },
        ),
        migrations.CreateModel(
            name="WarningNotice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("noticetype", models.CharField(max_length=8, verbose_name="超限类型")),
                ("max_level", models.FloatField(verbose_name="最高水位")),
                ("noticetime", models.DateTimeField(verbose_name="通知时间")),
                (
                    "isSuccess",
                    models.BooleanField(default=False, verbose_name="通知发送状态"),
                ),
                (
                    "isCanceled",
                    models.BooleanField(default=False, verbose_name="通知确认状态"),
                ),
                ("canceltime", models.DateTimeField(null=True, verbose_name="确认时间")),
                (
                    "executor",
                    models.ForeignKey(
                        db_column="executor",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executor",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        db_column="station_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warning_notice",
                        to="api.stationinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "警告通知信息",
                "verbose_name_plural": "警告通知信息",
            },
        ),
        migrations.CreateModel(
            name="WarningCloseDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("detail", models.TextField(blank=True, null=True, verbose_name="详情")),
                (
                    "warning",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.warningnotice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WaterInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("times", models.DateTimeField(verbose_name="上报时间")),
                ("rains", models.FloatField(null=True, verbose_name="降水量")),
                ("waterlevels", models.FloatField(null=True, verbose_name="水位")),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waterinfo",
                        to="api.stationinfo",
                        verbose_name="站点编号",
                    ),
                ),
            ],
            options={
                "verbose_name": "水位信息",
                "verbose_name_plural": "水位信息",
            },
        ),
        migrations.CreateModel(
            name="WaterPred",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("times", models.DateTimeField(verbose_name="预测起始时间")),
                ("waterlevel1", models.FloatField(verbose_name="time+1")),
                ("waterlevel2", models.FloatField(verbose_name="time+2")),
                ("waterlevel3", models.FloatField(verbose_name="time+3")),
                ("waterlevel4", models.FloatField(verbose_name="time+4")),
                ("waterlevel5", models.FloatField(verbose_name="time+5")),
                ("waterlevel6", models.FloatField(verbose_name="time+6")),
                (
                    "station",
                    models.ForeignKey(
                        db_column="station_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="water_pred",
                        to="api.stationinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "水位预测信息",
                "verbose_name_plural": "水位预测信息",
            },
        ),
    ]
