# Generated by Django 5.1.8 on 2025-04-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaterPred",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("times", models.DateTimeField(verbose_name="预测起始时间")),
                ("waterlevel1", models.FloatField(verbose_name="time+1")),
                ("waterlevel2", models.FloatField(verbose_name="time+2")),
                ("waterlevel3", models.FloatField(verbose_name="time+3")),
                ("waterlevel4", models.FloatField(verbose_name="time+4")),
                ("waterlevel5", models.FloatField(verbose_name="time+5")),
                ("waterlevel6", models.FloatField(verbose_name="time+6")),
            ],
        ),
    ]
