# Generated by Django 5.1.8 on 2025-04-10 07:49

from django.db import migrations
from django.contrib.auth.models import Group, Permission


def create_groups(apps, schema_editor):
    Group.objects.get_or_create(name='管理员组')
    Group.objects.get_or_create(name='普通用户组')


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(create_groups),
    ]
