# Generated by Django 5.1.7 on 2025-03-31 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LSTMModels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='LSTM_Models/')),
                ('rmse', models.FloatField()),
                ('md5', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScalerPT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='ScalerPT_Models/')),
                ('lstm_model', models.ForeignKey(db_column='lstm_md5', on_delete=django.db.models.deletion.CASCADE, related_name='scalers', to='lstm.lstmmodels', to_field='md5')),
            ],
        ),
        migrations.CreateModel(
            name='TrainResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='TrainResult/')),
                ('lstm_model', models.ForeignKey(db_column='lstm_md5', on_delete=django.db.models.deletion.CASCADE, related_name='train_res', to='lstm.lstmmodels', to_field='md5')),
            ],
        ),
    ]
