# Generated by Django 5.1.8 on 2025-04-11 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LSTMModels",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("input_size", models.IntegerField()),
                ("hidden_size", models.IntegerField()),
                ("output_size", models.IntegerField()),
                ("file", models.FileField(upload_to="LSTM_Models/")),
                ("rmse", models.FloatField()),
                ("md5", models.CharField(max_length=32, unique=True)),
                ("is_activate", models.BooleanField(default=False)),
                (
                    "station",
                    models.ForeignKey(
                        db_column="station_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lstm_model",
                        to="api.stationinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PredictDependence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dependence", models.JSONField(verbose_name="训练数据构成")),
                (
                    "station",
                    models.OneToOneField(
                        db_column="station_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predict_depend",
                        to="api.stationinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScalerPT",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(upload_to="ScalerPT_Models/")),
                (
                    "lstm_model",
                    models.ForeignKey(
                        db_column="lstm_md5",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scalers",
                        to="lstm.lstmmodels",
                        to_field="md5",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="TrainResult/")),
                (
                    "lstm_model",
                    models.ForeignKey(
                        db_column="lstm_md5",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="train_res",
                        to="lstm.lstmmodels",
                        to_field="md5",
                    ),
                ),
            ],
        ),
    ]
